#!/bin/bash
python models/final_testing_of_rnn_model.py out/train/coords_f1_run1/my_best_gru_model.epoch12-acc0.64.hdf5 gru coords 1 1 test2
python models/final_testing_of_rnn_model.py out/train/coords_f1_run2/my_best_gru_model.epoch11-acc0.59.hdf5 gru coords 1 2 test2
python models/final_testing_of_rnn_model.py out/train/coords_f1_run3/my_best_gru_model.epoch14-acc0.61.hdf5 gru coords 1 3 test2
python models/final_testing_of_rnn_model.py out/train/coords_f1_run4/my_best_gru_model.epoch12-acc0.60.hdf5 gru coords 1 4 test2
python models/final_testing_of_rnn_model.py out/train/coords_f1_run5/my_best_gru_model.epoch01-acc0.52.hdf5 gru coords 1 5 test2
python models/final_testing_of_rnn_model.py out/train/coords_f1_run6/my_best_gru_model.epoch05-acc0.70.hdf5 gru coords 1 6 test2
python models/final_testing_of_rnn_model.py out/train/coords_f1_run7/my_best_gru_model.epoch12-acc0.74.hdf5 gru coords 1 7 test2
python models/final_testing_of_rnn_model.py out/train/coords_f1_run8/my_best_gru_model.epoch15-acc0.74.hdf5 gru coords 1 8 test2
python models/final_testing_of_rnn_model.py out/train/coords_f1_run9/my_best_gru_model.epoch06-acc0.64.hdf5 gru coords 1 9 test2
python models/final_testing_of_rnn_model.py out/train/coords_f1_run10/my_best_gru_model.epoch05-acc0.74.hdf5 gru coords 1 10 test2
python models/final_testing_of_rnn_model.py out/train/coords_f2_run1/my_best_gru_model.epoch05-acc0.74.hdf5 gru coords 2 1 test2
python models/final_testing_of_rnn_model.py out/train/coords_f2_run2/my_best_gru_model.epoch10-acc0.79.hdf5 gru coords 2 2 test2
python models/final_testing_of_rnn_model.py out/train/coords_f2_run3/my_best_gru_model.epoch07-acc0.84.hdf5 gru coords 2 3 test2
python models/final_testing_of_rnn_model.py out/train/coords_f2_run4/my_best_gru_model.epoch10-acc0.99.hdf5 gru coords 2 4 test2
python models/final_testing_of_rnn_model.py out/train/coords_f2_run5/my_best_gru_model.epoch09-acc0.85.hdf5 gru coords 2 5 test2
python models/final_testing_of_rnn_model.py out/train/coords_f2_run6/my_best_gru_model.epoch08-acc0.83.hdf5 gru coords 2 6 test2
python models/final_testing_of_rnn_model.py out/train/coords_f2_run7/my_best_gru_model.epoch12-acc0.84.hdf5 gru coords 2 7 test2
python models/final_testing_of_rnn_model.py out/train/coords_f2_run8/my_best_gru_model.epoch01-acc0.83.hdf5 gru coords 2 8 test2
python models/final_testing_of_rnn_model.py out/train/coords_f2_run9/my_best_gru_model.epoch09-acc0.83.hdf5 gru coords 2 9 test2
python models/final_testing_of_rnn_model.py out/train/coords_f2_run10/my_best_gru_model.epoch09-acc0.85.hdf5 gru coords 2 10 test2
python models/final_testing_of_rnn_model.py out/train/coords_f3_run1/my_best_gru_model.epoch06-acc0.85.hdf5 gru coords 3 1 test2
python models/final_testing_of_rnn_model.py out/train/coords_f3_run2/my_best_gru_model.epoch05-acc0.64.hdf5 gru coords 3 2 test2
python models/final_testing_of_rnn_model.py out/train/coords_f3_run3/my_best_gru_model.epoch02-acc0.74.hdf5 gru coords 3 3 test2
python models/final_testing_of_rnn_model.py out/train/coords_f3_run4/my_best_gru_model.epoch02-acc0.74.hdf5 gru coords 3 4 test2
python models/final_testing_of_rnn_model.py out/train/coords_f3_run5/my_best_gru_model.epoch07-acc0.55.hdf5 gru coords 3 5 test2
python models/final_testing_of_rnn_model.py out/train/coords_f3_run6/my_best_gru_model.epoch01-acc0.58.hdf5 gru coords 3 6 test2
python models/final_testing_of_rnn_model.py out/train/coords_f3_run7/my_best_gru_model.epoch09-acc0.74.hdf5 gru coords 3 7 test2
python models/final_testing_of_rnn_model.py out/train/coords_f3_run8/my_best_gru_model.epoch10-acc0.74.hdf5 gru coords 3 8 test2
python models/final_testing_of_rnn_model.py out/train/coords_f3_run9/my_best_gru_model.epoch03-acc0.73.hdf5 gru coords 3 9 test2
python models/final_testing_of_rnn_model.py out/train/coords_f3_run10/my_best_gru_model.epoch11-acc0.69.hdf5 gru coords 3 10 test2
python models/final_testing_of_rnn_model.py out/train/coords_f4_run1/my_best_gru_model.epoch03-acc0.77.hdf5 gru coords 4 1 test2
python models/final_testing_of_rnn_model.py out/train/coords_f4_run2/my_best_gru_model.epoch05-acc0.53.hdf5 gru coords 4 2 test2
python models/final_testing_of_rnn_model.py out/train/coords_f4_run3/my_best_gru_model.epoch11-acc0.52.hdf5 gru coords 4 3 test2
python models/final_testing_of_rnn_model.py out/train/coords_f4_run4/my_best_gru_model.epoch01-acc0.52.hdf5 gru coords 4 4 test2
python models/final_testing_of_rnn_model.py out/train/coords_f4_run5/my_best_gru_model.epoch02-acc0.74.hdf5 gru coords 4 5 test2
python models/final_testing_of_rnn_model.py out/train/coords_f4_run6/my_best_gru_model.epoch03-acc0.74.hdf5 gru coords 4 6 test2
python models/final_testing_of_rnn_model.py out/train/coords_f4_run7/my_best_gru_model.epoch01-acc0.52.hdf5 gru coords 4 7 test2
python models/final_testing_of_rnn_model.py out/train/coords_f4_run8/my_best_gru_model.epoch06-acc0.55.hdf5 gru coords 4 8 test2
python models/final_testing_of_rnn_model.py out/train/coords_f4_run9/my_best_gru_model.epoch01-acc0.52.hdf5 gru coords 4 9 test2
python models/final_testing_of_rnn_model.py out/train/coords_f4_run10/my_best_gru_model.epoch01-acc0.52.hdf5 gru coords 4 10 test2
python models/final_testing_of_rnn_model.py out/train/coords_f5_run1/my_best_gru_model.epoch01-acc0.52.hdf5 gru coords 5 1 test2
python models/final_testing_of_rnn_model.py out/train/coords_f5_run2/my_best_gru_model.epoch01-acc0.52.hdf5 gru coords 5 2 test2
python models/final_testing_of_rnn_model.py out/train/coords_f5_run3/my_best_gru_model.epoch02-acc0.54.hdf5 gru coords 5 3 test2
python models/final_testing_of_rnn_model.py out/train/coords_f5_run4/my_best_gru_model.epoch03-acc0.53.hdf5 gru coords 5 4 test2
python models/final_testing_of_rnn_model.py out/train/coords_f5_run5/my_best_gru_model.epoch01-acc0.58.hdf5 gru coords 5 5 test2
python models/final_testing_of_rnn_model.py out/train/coords_f5_run6/my_best_gru_model.epoch06-acc0.60.hdf5 gru coords 5 6 test2
python models/final_testing_of_rnn_model.py out/train/coords_f5_run7/my_best_gru_model.epoch01-acc0.52.hdf5 gru coords 5 7 test2
python models/final_testing_of_rnn_model.py out/train/coords_f5_run8/my_best_gru_model.epoch01-acc0.52.hdf5 gru coords 5 8 test2
python models/final_testing_of_rnn_model.py out/train/coords_f5_run9/my_best_gru_model.epoch05-acc0.53.hdf5 gru coords 5 9 test2
python models/final_testing_of_rnn_model.py out/train/coords_f5_run10/my_best_gru_model.epoch08-acc0.59.hdf5 gru coords 5 10 test2
python models/final_testing_of_rnn_model.py out/train/angles_f1_run1/my_best_gru_model.epoch11-acc0.57.hdf5 gru angles 1 1  test2
python models/final_testing_of_rnn_model.py out/train/angles_f1_run2/my_best_gru_model.epoch06-acc0.57.hdf5 gru angles 1 2 test2
python models/final_testing_of_rnn_model.py out/train/angles_f1_run3/my_best_gru_model.epoch15-acc0.58.hdf5 gru angles 1 3 test2
python models/final_testing_of_rnn_model.py out/train/angles_f1_run4/my_best_gru_model.epoch12-acc0.58.hdf5 gru angles 1 4 test2
python models/final_testing_of_rnn_model.py out/train/angles_f1_run5/my_best_gru_model.epoch12-acc0.57.hdf5 gru angles 1 5 test2
python models/final_testing_of_rnn_model.py out/train/angles_f1_run6/my_best_gru_model.epoch14-acc0.59.hdf5 gru angles 1 6 test2
python models/final_testing_of_rnn_model.py out/train/angles_f1_run7/my_best_gru_model.epoch13-acc0.57.hdf5 gru angles 1 7 test2
python models/final_testing_of_rnn_model.py out/train/angles_f1_run8/my_best_gru_model.epoch12-acc0.58.hdf5 gru angles 1 8 test2
python models/final_testing_of_rnn_model.py out/train/angles_f1_run9/my_best_gru_model.epoch02-acc0.57.hdf5 gru angles 1 9 test2
python models/final_testing_of_rnn_model.py out/train/angles_f1_run10/my_best_gru_model.epoch08-acc0.57.hdf5 gru angles 1 10 test2
python models/final_testing_of_rnn_model.py out/train/angles_f2_run1/my_best_gru_model.epoch03-acc0.52.hdf5 gru angles 2 1 test2
python models/final_testing_of_rnn_model.py out/train/angles_f2_run2/my_best_gru_model.epoch02-acc0.52.hdf5 gru angles 2 2 test2
python models/final_testing_of_rnn_model.py out/train/angles_f2_run3/my_best_gru_model.epoch01-acc0.52.hdf5 gru angles 2 3 test2
python models/final_testing_of_rnn_model.py out/train/angles_f2_run4/my_best_gru_model.epoch03-acc0.52.hdf5 gru angles 2 4 test2
python models/final_testing_of_rnn_model.py out/train/angles_f2_run5/my_best_gru_model.epoch02-acc0.52.hdf5 gru angles 2 5 test2
python models/final_testing_of_rnn_model.py out/train/angles_f2_run6/my_best_gru_model.epoch01-acc0.52.hdf5 gru angles 2 6 test2
python models/final_testing_of_rnn_model.py out/train/angles_f2_run7/my_best_gru_model.epoch02-acc0.52.hdf5 gru angles 2 7 test2
python models/final_testing_of_rnn_model.py out/train/angles_f2_run8/my_best_gru_model.epoch01-acc0.52.hdf5 gru angles 2 8 test2
python models/final_testing_of_rnn_model.py out/train/angles_f2_run9/my_best_gru_model.epoch02-acc0.52.hdf5 gru angles 2 9 test2
python models/final_testing_of_rnn_model.py out/train/angles_f2_run10/my_best_gru_model.epoch01-acc0.52.hdf5 gru angles 2 10 test2
python models/final_testing_of_rnn_model.py out/train/angles_f3_run2/my_best_gru_model.epoch09-acc0.56.hdf5 gru angles 3 2 test2
python models/final_testing_of_rnn_model.py out/train/angles_f3_run3/my_best_gru_model.epoch02-acc0.55.hdf5 gru angles 3 3 test2
python models/final_testing_of_rnn_model.py out/train/angles_f3_run4/my_best_gru_model.epoch06-acc0.55.hdf5 gru angles 3 4 test2
python models/final_testing_of_rnn_model.py out/train/angles_f3_run5/my_best_gru_model.epoch03-acc0.55.hdf5 gru angles 3 5 test2
python models/final_testing_of_rnn_model.py out/train/angles_f3_run6/my_best_gru_model.epoch15-acc0.55.hdf5 gru angles 3 6 test2
python models/final_testing_of_rnn_model.py out/train/angles_f3_run7/my_best_gru_model.epoch07-acc0.55.hdf5 gru angles 3 7 test2
python models/final_testing_of_rnn_model.py out/train/angles_f3_run8/my_best_gru_model.epoch05-acc0.55.hdf5 gru angles 3 8 test2
python models/final_testing_of_rnn_model.py out/train/angles_f3_run9/my_best_gru_model.epoch02-acc0.55.hdf5 gru angles 3 9 test2
python models/final_testing_of_rnn_model.py out/train/angles_f3_run10/my_best_gru_model.epoch11-acc0.55.hdf5 gru angles 3 10 test2
python models/final_testing_of_rnn_model.py out/train/angles_f3_run11/my_best_gru_model.epoch07-acc0.55.hdf5 gru angles 3 11 test2
